### ISSUE TITLE
Working examples

### ISSUE THREAD

**Issue by massich** [Semmle/lgtm-issue-tracker-example#4]
This example seems great, but I am not sure that I fully get it (maybe I've miss read some part of the readme or the tutorial). 

If I understood properly I should be able to pass the keys and this repo as Github action and LGTM should populate my GitHub issue tracker.

Do you have a list of projects that have it working so that we can see how it works?
or is it what we find in https://github.com/Semmle/demos/tree/master/lgtm_demos

**Comment by nickfyson** [comment]
Hi @massich! Thanks for your interest in LGTM, and I hope I can clarify things a bit...

As well as our public LGTM.com site for open-source projects we offer an enterprise version, and in that we give the option of exporting customer's alerts to an external issue tracker. This works by sending webhook POST requests to the external service, and in this repo we give a bare-bones example of how to write a server that acts as the translator between LGTM and Github Issues. Unfortunately this feature is only available to enterprise customers, so it's not possible to point you to any public working examples.

Hope that's helps make things clearer, and I'm going to open a PR now to improve the information we're providing in the README. Let me know if you have any further questions! 🙂

**Comment by massich** [comment]
ok cool.

Its a nice feature.
